#!/bin/bash
PERCENT=10
RUN=0
function USAGE {
	echo -e "
Usage: $0 [FLAGS]... [BITHORDE LINK FILE]\n
  -h, --help        Shows this help.
  -p, --percent     Load asset [NUM] percent before xdg-open, if requires -r flag. (DEFAULT WITH -r: 10, WITOUT -r: 100)
  -r, --run         Open asset with xdg-open after preload. (DEFAULT: No)\n
  Example: $0 -p 20 -r MyBithordeLink.avi\n"
}
if [ "$1" = "" ]; then
        echo "bhbuff needs a bithorde link to handle..."
	USAGE
        exit 1
fi
while [ $# -gt 0 ]; do 
  case "$1" in
    -h|--help)
	      USAGE
	      exit 0
	      ;;
    -r|--run)
              RUN=1
              ;;
    -p|--percent)
              PERCENT="$2"
              if [[ "$PERCENT" =~ ^[0-9]+$ ]]; then
			if [ "$PERCENT" -ge 100 ]; then
				PERCENT=100
			fi
		else
                	echo "Procent needs to be a number between 1 - 100..."
			USAGE
                	exit 1
              fi
              ;;
    *)
              FILE=${!#}
	      if ! [[ $(readlink "$FILE") == *magnet* ]]; then
		echo "File not a bithorde symlink..."
		USAGE
		exit 1
	      fi
		
	      ;;
  esac
  shift
done
if [ "$RUN" = 0 ]; then
	bhget -sy -py "$FILE" > /dev/null
else
	echo -e 'For progress, type: kill -USR1 $(pidof dd)\nin another terminal.'
	PIECETOLOAD="$(($(($(($(stat -L -c%s "$FILE")/100))*$PERCENT))/512))"
	dd if="$FILE" of=/dev/null bs=512 count=$PIECETOLOAD
	xdg-open "$FILE" > /dev/null 2> /dev/null
	dd if="$FILE" of=/dev/null bs=512 skip=$PIECETOLOAD
fi
